---
- name: Docker Pull della nuova immagine di identity-provider
  community.docker.docker_image:
      name: "{{ registry_url }}/{{ identity_provider_path }}"
      tag: "{{ image_tag }}"
      source: pull
      force_source: yes

- name: Stop e Rimozione vecchio container di identity-provider (se esiste)
  community.docker.docker_container:
      name: "{{ identity_provider_container_name }}"
      state: absent

- name: Avvio nuovo container di identity-provider (Docker Run)
  community.docker.docker_container:
      name: "{{ identity_provider_container_name }}"
      image: "{{ registry_url }}/{{ identity_provider_path }}:{{ image_tag }}"
      state: started
      restart_policy: always
      published_ports:
          - "{{ target_host_port }}:{{ internal_container_port }}"
      networks:
          - name: database-network

- name: Rimuovi immagini "dangling" (layer orfani)
  community.docker.docker_prune:
      images: yes
      images_filters:
          dangling: true
