---
- name: Login al Docker Registry sul server remoto
  community.docker.docker_login:
      registry: "{{ registry_url }}"
      username: "{{ registry_user }}"
      password: "{{ registry_pass }}"

- name: "Deploy identity-provider image"
  import_tasks: identity-provider-deploy.yml
