---
- name: Build and Push Docker Image
  hosts: builder
  vars_files:
      - vars/deploy.yml
  roles:
      - { role: builder }

- name: Deploy on Production Server
  hosts: staging
  vars_files:
      - vars/deploy.yml
  roles:
      - { role: project-deploy }
