name: Run Sonarqube
run-name: Sonarqube scan for ${{ gitea.actor }}

#on:
#    push:
#        branches:
#            - staging
on:
  workflow_dispatch
jobs:
    sonar-scan:
        runs-on: self-hosted
        environment: main
        container:
            image: dockerhub.newtimegroup.it/ci-runner:v1
            credentials:
                username: ${{ secrets.REGISTRY_USER }}
                password: ${{ secrets.REGISTRY_PASS }}
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
            with:
              fetch-depth: 0

          - name: SonarQube Scan
            env:
              SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
              SONAR_HOST_URL: ${{ inputs.SONAR_HOST_URL }}
            run: |
              # 1. Scarica lo scanner manualmente nella cartella corrente
              curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip

              # 2. Scompatta (usando l'unzip che abbiamo installato prima)
              unzip -q sonar-scanner.zip

              # 3. Esegui lo scanner puntando al binario appena scompattato
              ./sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner \
                -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.repository }} \
                -Dsonar.sources=. \
                -Dsonar.host.url=$SONAR_HOST_URL \
                -Dsonar.javascript.node.maxspace=2048 \
                -X
