name: Run Sonarqube
run-name: Sonarqube scan for ${{ gitea.actor }}

#on:
#    push:
#        branches:
#            - staging
on:
  workflow_dispatch
jobs:
    sonar-scan:
        runs-on: self-hosted
        environment: main
        container:
            image: dockerhub.newtimegroup.it/ci-runner:v1
            credentials:
                username: ${{ secrets.REGISTRY_USER }}
                password: ${{ secrets.REGISTRY_PASS }}
        steps:
          - name: 🚀 Notifica Inizio
            uses: https://${{ secrets.PAT_TOKEN }}@gitea.newtimegroup.it/New_Time_SPA/templates/discord-notifier@main
            with:
              webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
              event_type: "sonar_start"

          - name: Checkout Code
            uses: actions/checkout@v3
            with:
              fetch-depth: 0

          - name: SonarQube Scan
            id: sonar
            uses: https://${{ secrets.PAT_TOKEN }}@gitea.newtimegroup.it/New_Time_SPA/templates/sonarqube@main
            with:
              sonar_token: ${{ secrets.SONARQUBE_TOKEN }}
              sonar_host_url: ${{ vars.SONAR_HOST_URL }}
              webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
              args: >
                -Dsonar.projectKey=${{ gitea.repository_owner }}_${{ gitea.repository }}
                -Dsonar.sources=.
                -Dsonar.javascript.node.maxspace=2048
                -X

          - name: 🏁 Notifica Esito Finale
            if: always()
            uses: https://${{ secrets.PAT_TOKEN }}@gitea.newtimegroup.it/New_Time_SPA/templates/discord-notifier@main
            with:
              webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
              event_type: ${{ job.status == 'success' && 'sonar_success' || 'sonar_failure' }}
